name: rana_merchant
description: Aplikasi Kelola Toko & Pesanan UMKM.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.0.5
  
  # Networking
  dio: ^5.3.3
  
  # Local Storage (Offline First)
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.0
  sqflite_common_ffi: ^2.3.0 # Required for Desktop
  sqflite_common_ffi_web: ^0.4.0 # Required for Web

  # Audio
  audioplayers: ^5.1.0

  
  # UI Components
  google_fonts: ^6.1.0
  intl: ^0.18.1
  lucide_icons: ^0.257.0 # Or similar icon pack
  fl_chart: ^0.68.0 # For Reporting Charts
  url_launcher: ^6.1.11
  mobile_scanner: ^3.5.0 # [NEW] For QR Scanning
  image_picker: ^1.0.4 # [NEW] For Wallet Proof
  blue_thermal_printer: ^1.2.3 # [NEW] Thermal Printer
  permission_handler: ^11.0.1 # [NEW] Bluetooth Permissions
  screenshot: ^3.0.0 # [FIX] Upgrade for Flutter 3.19+
  share_plus: ^7.1.0 # [NEW] Share File
  path_provider: ^2.1.1 # [NEW] Temp Storage

  
  # Background Sync
  workmanager: ^0.7.0
  
  # UUID
  uuid: ^4.2.1
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_animate: ^4.5.2
  animations: ^2.1.0
  lottie: ^3.1.0
  flutter_local_notifications: ^17.0.0
  socket_io_client: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
