name: rana_market
description: Aplikasi Pesan Antar Makanan & Belanja UMKM.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  dio: ^5.3.2
  google_fonts: ^6.1.0
  intl: ^0.18.1
  url_launcher: ^6.1.11
  cached_network_image: ^3.3.0 # For product images
  geolocator: ^10.1.0 # Find nearby stores
  flutter_map: ^6.0.0 # OpenStreetMap for Location
  latlong2: ^0.9.0
  qr_flutter: ^4.1.0
  socket_io_client: ^2.0.3
  flutter_local_notifications: ^17.1.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
